#!/usr/bin/env bash
(scp src/main.rs "$(cat pi-ip.txt)":"$(cat gst-examples-dir.txt)/webrtc/sendrecv/gst-rust/src/" && \
sleep 3 && \
scp id.txt "$(cat pi-ip.txt)":"$(cat gst-examples-dir.txt)/webrtc/sendrecv/gst-rust/remote-id.txt") & \
GST_DEBUG="*webrtc*:7" LD_LIBRARY_PATH="$(cat ~/.libnice-library-path.txt)" cargo run --
